#!/bin/sh
#Opens terminal's Enviroment
gnome-terminal --geometry 95x18+0+535 --hide-menubar --title Bottom-Left --working-directory=/mnt/additional/repos
gnome-terminal --geometry 82x59-0+10 --hide-menubar --title Right --window-with-profile="nighty (Right)" --working-directory=/mnt/additional/repos -- sh /home/gusto/bin/scripts/.dev_profile 
gnome-terminal --geometry 95x18+0+10 --hide-menubar --title Top-Left --working-directory=/mnt/additional/repos #--window-with-profile="nighty (Right)" -- sh /home/gusto/.dev_profile
