#!/bin/sh
#Opens terminal's Enviroment
gnome-terminal --geometry 151x28-1255+535 --hide-menubar --title Bottom-Left
gnome-terminal --geometry 82x59-20+10 --hide-menubar --title Right --window-with-profile="nighty (Right)" -- sh /home/gusto/bin/scripts/.dev_profile 
gnome-terminal --geometry 151x28-1255+10 --hide-menubar --title Top-Left
