#!/bin/sh
#Opens terminal's Enviroment
gnome-terminal --geometry 84x18-1000+555 --hide-menubar --title Bottom-Left
gnome-terminal --geometry 84x18-1000+50 --hide-menubar --title Top-Left
gnome-terminal --geometry 70x59+3525+40 --hide-menubar --title Right --window-with-profile="nighty (Right)" -- sh /home/gusto/bin/scripts/.dev_profile 
